rancher:
  container_name: "rancher"
  restart: always
  image: rancher/server
  ports:
  - 8080:8080
  environment:
  - VIRTUAL_HOST=rancher.o2
  - VIRTUAL_PORT=8080
  volumes:
  - '/srv/rancher/mysql:/var/lib/mysql:rw'
